# Generated by Django 5.2 on 2025-07-02 02:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=20)),
                ('adminPwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'admininfo',
            },
        ),
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('busId', models.AutoField(primary_key=True, serialize=False)),
                ('busType', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'businfo',
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customerinfo',
            },
        ),
        migrations.CreateModel(
            name='DatabaseInfo',
            fields=[
                ('databaseId', models.AutoField(primary_key=True, serialize=False)),
                ('databasetype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'databaseinfo',
            },
        ),
        migrations.CreateModel(
            name='EitInfo',
            fields=[
                ('eitid', models.AutoField(primary_key=True, serialize=False)),
                ('eittype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'eitinfo',
            },
        ),
        migrations.CreateModel(
            name='EngineerInfo',
            fields=[
                ('engineerId', models.AutoField(primary_key=True, serialize=False)),
                ('engineerName', models.CharField(max_length=20)),
                ('telephoneno', models.CharField(max_length=30)),
                ('engineerpwd', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'engineerinfo',
            },
        ),
        migrations.CreateModel(
            name='MachineInfo',
            fields=[
                ('machineid', models.AutoField(primary_key=True, serialize=False)),
                ('machinetype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'machineinfo',
            },
        ),
        migrations.CreateModel(
            name='OpcInfo',
            fields=[
                ('opcid', models.AutoField(primary_key=True, serialize=False)),
                ('opctype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'opcinfo',
            },
        ),
        migrations.CreateModel(
            name='OsInfo',
            fields=[
                ('osid', models.AutoField(primary_key=True, serialize=False)),
                ('ostype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'osinfo',
            },
        ),
        migrations.CreateModel(
            name='PlcInfo',
            fields=[
                ('plcid', models.AutoField(primary_key=True, serialize=False)),
                ('plctype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'plcinfo',
            },
        ),
        migrations.CreateModel(
            name='ProjInfo',
            fields=[
                ('projid', models.AutoField(primary_key=True, serialize=False)),
                ('projno', models.CharField(max_length=10)),
                ('plannedwh', models.IntegerField(default=0)),
                ('lacation', models.CharField(max_length=30)),
                ('projstatusid', models.IntegerField(default=0)),
                ('projdescription', models.CharField(max_length=300)),
                ('customerid', models.IntegerField(default=0)),
                ('startingtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('opcstatus', models.CharField(max_length=10)),
                ('serverstatus', models.CharField(max_length=10)),
                ('osstatus', models.CharField(max_length=10)),
                ('databasestatus', models.CharField(max_length=10)),
                ('opcidgroup', models.CharField(max_length=20)),
                ('serverid', models.IntegerField(default=0)),
                ('databaseid', models.IntegerField(default=0)),
                ('kodate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'projinfo',
            },
        ),
        migrations.CreateModel(
            name='ProjStatus',
            fields=[
                ('projStatusId', models.AutoField(primary_key=True, serialize=False)),
                ('projstatustype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'projstatus',
            },
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('serverid', models.AutoField(primary_key=True, serialize=False)),
                ('servertype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'serverinfo',
            },
        ),
        migrations.CreateModel(
            name='WbsInfo',
            fields=[
                ('wbsid', models.AutoField(primary_key=True, serialize=False)),
                ('wbsno', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'wbsinfo',
            },
        ),
        migrations.CreateModel(
            name='WorkHourInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projid', models.IntegerField(default=0)),
                ('workdate', models.DateField()),
                ('onsite', models.CharField(max_length=10)),
                ('engineerid', models.IntegerField(default=0)),
                ('wbsid', models.IntegerField(default=0)),
                ('wh', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=50)),
                ('weekno', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'workhourinfo',
            },
        ),
    ]
