# Generated by Django 5.2 on 2025-07-03 07:37

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eitpm01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projinfo',
            old_name='lacation',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='engineerinfo',
            name='engineerId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='工程师编号'),
        ),
        migrations.AlterField(
            model_name='engineerinfo',
            name='engineerName',
            field=models.CharField(max_length=20, verbose_name='工程师名称'),
        ),
        migrations.AlterField(
            model_name='engineerinfo',
            name='engineerpwd',
            field=models.CharField(max_length=30, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='engineerinfo',
            name='telephoneno',
            field=models.CharField(max_length=30, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='kodate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='startingtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
