# Generated by Django 5.2 on 2025-07-03 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eitpm01', '0002_rename_lacation_projinfo_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projinfo',
            name='customerid',
            field=models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, to='eitpm01.customerinfo'),
        ),
    ]
