# Generated by Django 5.2 on 2025-07-03 09:16

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eitpm01', '0003_alter_projinfo_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projinfo',
            name='customerid',
            field=models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.CASCADE, to='eitpm01.customerinfo', verbose_name='客户ID'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='databaseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eitpm01.databaseinfo', verbose_name='数据库ID'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='databasestatus',
            field=models.CharField(max_length=10, verbose_name='数据库状态'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='kodate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='KO日期'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='location',
            field=models.CharField(max_length=30, verbose_name='项目地点'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='opcidgroup',
            field=models.CharField(max_length=20, verbose_name='OPC组ID'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='opcstatus',
            field=models.CharField(max_length=10, verbose_name='OPC状态'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='osstatus',
            field=models.CharField(max_length=10, verbose_name='操作系统状态'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='plannedwh',
            field=models.IntegerField(default=0, verbose_name='计划工时'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='projdescription',
            field=models.CharField(max_length=300, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='projid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='projno',
            field=models.CharField(max_length=10, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='projstatusid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eitpm01.projstatus', verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='serverid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eitpm01.serverinfo', verbose_name='服务器ID'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='serverstatus',
            field=models.CharField(max_length=10, verbose_name='服务器状态'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='startingtime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='项目开始时间'),
        ),
    ]
