# Generated by Django 5.2 on 2025-07-03 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eitpm01', '0004_alter_projinfo_customerid_alter_projinfo_databaseid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projinfo',
            name='databaseid',
            field=models.ForeignKey(db_column='databaseid', on_delete=django.db.models.deletion.CASCADE, to='eitpm01.databaseinfo', verbose_name='数据库ID'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='projstatusid',
            field=models.ForeignKey(db_column='projstatusid', on_delete=django.db.models.deletion.CASCADE, to='eitpm01.projstatus', verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='projinfo',
            name='serverid',
            field=models.ForeignKey(db_column='serverid', on_delete=django.db.models.deletion.CASCADE, to='eitpm01.serverinfo', verbose_name='服务器ID'),
        ),
    ]
